Repository course-dprep/yelp-influencers-takeout-ratings, pull requests merged in 2024-09, with the labels that each got.

#13 Update README.md
  README.md
Labels: documentation

#15 Update README.md
  README.md
Labels: documentation

#25 Add files via upload
  matching_elite_format.R
  matching_elite_format.py
Labels: enhancement

#26 Commit Quarto file
  Group Report.qmd
Labels: documentation

#27 prepare_data.R
  prepare_data.R
Labels: enhancement

#28 prepare_data.R
  prepare_data.R
Labels: bug

#36 README.md
  README.md
Labels: documentation

#38 Group Report.qmd
  Group Report.qmd
Labels: enhancement

#40 Remove business features factor in reseach question
  README.md
Labels: documentation

#52 missing the result folder
  7. results/placeholder.txt
Labels: enhancement

#54 Update preprocessing data
  6. source_code/preprocessing_data.R
  updated-project.Rproj
Labels: enhancement

#58 update the document
  1. docs/Group Report.qmd
Labels: documentation

#62 testing makefile script
  6-source_code/download_data.R
  6-source_code/prepare_data.R
  6-source_code/preprocessing_data.R
  makefile
Labels: enhancement

#64 delete LICENSE file
  LICENSE
Labels: duplicate

#74 add plots code
  6-source_code/0_install_packages.R
  6-source_code/4_plot_data.R
  7-plots/placeholder.txt
  8-results/placeholder.txt
  makefile
Labels: enhancement

#76 add auto makefile for plots
  6-source_code/0_install_packages.R
  6-source_code/3_preprocessing_data.R
  7-plots/avg_rating_gt_1000_by_division.png
  7-plots/avg_rating_gt_1000_by_is_open.png
  7-plots/avg_rating_lt_1000_by_division.png
  7-plots/avg_rating_lt_1000_by_is_open.png
  7-plots/avg_rating_takeout_by_elite_status.png
  7-plots/correlation_matrix_heatmap.png
  7-plots/distribution_ratings_takeout_by_division_and_elite_status.png
  7-plots/distribution_ratings_takeout_by_elite_status.png
  7-plots/distribution_review_count_business_by_is_open.png
  7-plots/distribution_user_ratings_by_elite_review.png
  7-plots/relationship_fans_user_rating_faceted_by_division.png
  7-plots/user_ratings_by_division_elite_review.png
  makefile
Labels: enhancement

#78 initial analysis
  6-source_code/0_install_packages.R
  6-source_code/5_analyse_data.R
  8-results/anova_summary.png
  8-results/anova_summary.txt
  8-results/normal_qq_plot.png
  8-results/scale_location_plot.png
Labels: enhancement

#80 group report
  1-docs/Group Report.qmd
Labels: bug
