Repository course-dprep/yelp-influencers-takeout-ratings, pull requests merged in 2024-10, with the labels that each got.

#97 add readme
  README.md
Labels: documentation

#99 changed plot code
  6-source_code/4_plot_data.R
  7-plots/avg_rating_gt_1000_by_division.png
  7-plots/avg_rating_gt_1000_by_is_open.png
  7-plots/avg_rating_gt_1000_by_region.png
  7-plots/avg_rating_lt_1000_by_division.png
  7-plots/avg_rating_lt_1000_by_is_open.png
  7-plots/avg_rating_lt_1000_by_region.png
  7-plots/avg_rating_takeout_by_elite_review.png
  7-plots/avg_rating_takeout_by_elite_status.png
  7-plots/correlation_matrix_heatmap.png
  7-plots/distribution_ratings_takeout_by_division_and_elite_status.png
  7-plots/distribution_ratings_takeout_by_elite_review.png
  7-plots/distribution_ratings_takeout_by_elite_status.png
  7-plots/distribution_ratings_takeout_by_region_and_elite_review.png
  7-plots/distribution_user_ratings_by_elite_review.png
  7-plots/relationship_fans_user_rating_faceted_by_division.png
  7-plots/relationship_fans_user_rating_faceted_by_region.png
  7-plots/user_ratings_by_division_elite_review.png
  7-plots/user_ratings_by_region_elite_review.png
Labels: bug

#102 add packages
  6-source_code/0_install_packages.R
Labels: enhancement

#105 update code for drawing plots
  6-source_code/0_install_packages.R
  6-source_code/4_plot_data.R
  6-source_code/5_analyse_data.R
  7-plots/avg_rating_takeout_by_elite_review.png
  7-plots/correlation_matrix_heatmap.png
  7-plots/distribution_ratings_takeout_by_region_and_elite_review.png
Labels: enhancement

#107 upgrade makefile + group report
  1-docs/Group_Report.qmd
  1-docs/Group_Report_v2.qmd
  6-source_code/4_plot_data.R
  6-source_code/5_analyse_data.R
  8-results/anova_normal_qq_plot.png
  8-results/anova_scale_location_plot.png
  8-results/anova_summary.png
  8-results/anova_summary.txt
  8-results/normal_qq_plot.png
  8-results/pairwise_t_test_summary.txt
  8-results/regression_normal_qq_plot.png
  8-results/regression_residuals_fitted_plot.png
  8-results/regression_summary.txt
  8-results/scale_location_plot.png
  8-results/tukey_hsd_summary.txt
  makefile
Labels: documentation

#111 new make file
  makefile
Labels: bug

#114 fix group report
  1-docs/Group_Report.qmd
  1-docs/Group_Report_v2.qmd
  6-source_code/5_analyse_data.R
Labels: bug

#120 add new
  1-docs/Group_Report.html
  1-docs/Group_Report.qmd
  1-docs/Group_Report_files/figure-html/unnamed-chunk-33-1.png
  1-docs/Group_Report_files/figure-html/unnamed-chunk-34-1.png
  1-docs/Group_Report_files/figure-html/unnamed-chunk-37-1.png
  1-docs/Group_Report_files/figure-html/unnamed-chunk-38-1.png
  1-docs/Group_Report_files/libs/bootstrap/bootstrap-icons.css
  1-docs/Group_Report_files/libs/bootstrap/bootstrap-icons.woff
  1-docs/Group_Report_files/libs/bootstrap/bootstrap.min.css
  1-docs/Group_Report_files/libs/bootstrap/bootstrap.min.js
  1-docs/Group_Report_files/libs/clipboard/clipboard.min.js
  1-docs/Group_Report_files/libs/quarto-html/anchor.min.js
  1-docs/Group_Report_files/libs/quarto-html/popper.min.js
  1-docs/Group_Report_files/libs/quarto-html/quarto-syntax-highlighting.css
  1-docs/Group_Report_files/libs/quarto-html/quarto.js
  1-docs/Group_Report_files/libs/quarto-html/tippy.css
  1-docs/Group_Report_files/libs/quarto-html/tippy.umd.min.js
  1-docs/images/avg_rating_gt_1000_by_is_open.png
  1-docs/images/avg_rating_gt_1000_by_region.png
  1-docs/images/avg_rating_lt_1000_by_is_open.png
  1-docs/images/avg_rating_lt_1000_by_region.png
  1-docs/images/distribution_ratings_takeout_by_elite_review.png
  1-docs/images/distribution_review_count_business_by_is_open.png
  1-docs/images/distribution_user_ratings_by_elite_review.png
  1-docs/images/relationship_fans_user_rating_faceted_by_region.png
  1-docs/images/user_ratings_by_region_elite_review.png
  6-source_code/3_preprocessing_data.R
Labels: enhancement

#122 run the flow successfully
  1-docs/Group_Report.html
  1-docs/Group_Report.qmd
  1-docs/Group_Report_files/figure-html/unnamed-chunk-27-1.png
  1-docs/Group_Report_files/figure-html/unnamed-chunk-28-1.png
  1-docs/Group_Report_files/figure-html/unnamed-chunk-31-1.png
  1-docs/Group_Report_files/figure-html/unnamed-chunk-32-1.png
  1-docs/Group_Report_files/libs/bootstrap/bootstrap-icons.css
  1-docs/Group_Report_files/libs/bootstrap/bootstrap-icons.woff
  1-docs/Group_Report_files/libs/bootstrap/bootstrap.min.css
  1-docs/Group_Report_files/libs/bootstrap/bootstrap.min.js
  1-docs/Group_Report_files/libs/clipboard/clipboard.min.js
  1-docs/Group_Report_files/libs/quarto-html/anchor.min.js
  1-docs/Group_Report_files/libs/quarto-html/popper.min.js
  1-docs/Group_Report_files/libs/quarto-html/quarto-syntax-highlighting.css
  1-docs/Group_Report_files/libs/quarto-html/quarto.js
  1-docs/Group_Report_files/libs/quarto-html/tippy.css
  1-docs/Group_Report_files/libs/quarto-html/tippy.umd.min.js
  1-docs/images/avg_rating_gt_1000_by_is_open.png
  1-docs/images/avg_rating_gt_1000_by_region.png
  1-docs/images/avg_rating_lt_1000_by_is_open.png
  1-docs/images/avg_rating_lt_1000_by_region.png
  1-docs/images/distribution_ratings_takeout_by_elite_review-01.png
  1-docs/images/distribution_ratings_takeout_by_elite_review.png
  1-docs/images/distribution_review_count_business_by_is_open-01.png
  1-docs/images/distribution_review_count_business_by_is_open.png
  1-docs/images/distribution_user_ratings_by_elite_review.png
  1-docs/images/user_ratings_by_region_elite_review.png
Labels: documentation

#130 check makefile automation
  1-docs/Group_Report.html
Labels: enhancement

#131 updated analysis
  6-source_code/5_analyse_data.R
  8-results/anova_summary.txt
  8-results/regression_summary.txt
Labels: documentation, enhancement

#138 done checking full flow
  1-docs/Group_Report.html
  1-docs/Group_Report_files/figure-html/unnamed-chunk-19-1.png
  1-docs/Group_Report_files/figure-html/unnamed-chunk-20-1.png
  1-docs/Group_Report_files/figure-html/unnamed-chunk-23-1.png
  1-docs/Group_Report_files/figure-html/unnamed-chunk-24-1.png
  1-docs/Group_Report_files/libs/bootstrap/bootstrap-icons.css
  1-docs/Group_Report_files/libs/bootstrap/bootstrap-icons.woff
  1-docs/Group_Report_files/libs/bootstrap/bootstrap.min.css
  1-docs/Group_Report_files/libs/bootstrap/bootstrap.min.js
  1-docs/Group_Report_files/libs/clipboard/clipboard.min.js
  1-docs/Group_Report_files/libs/quarto-html/anchor.min.js
  1-docs/Group_Report_files/libs/quarto-html/popper.min.js
  1-docs/Group_Report_files/libs/quarto-html/quarto-syntax-highlighting.css
  1-docs/Group_Report_files/libs/quarto-html/quarto.js
  1-docs/Group_Report_files/libs/quarto-html/tippy.css
  1-docs/Group_Report_files/libs/quarto-html/tippy.umd.min.js
Labels: enhancement

#141 run full flow to ANOVA analysis
  1-docs/Group_Report.html
  1-docs/Group_Report.qmd
  6-source_code/0_install_packages.R
Labels: enhancement

#144 double check the run with new implementation
  1-docs/Group_Report.html
  1-docs/Group_Report.qmd
  1-docs/Group_Report_files/figure-html/unnamed-chunk-23-1.png
  1-docs/Group_Report_files/figure-html/unnamed-chunk-24-1.png
  8-results/anova_summary.txt
  8-results/regression_summary.txt
Labels: enhancement

#162 add packages
  6-source_code/0_install_packages.R
  README.md
Labels: bug
